# -*- coding: utf-8 -*-
"""Dahlia-Lachica-grade8-library-NB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTsEAFlMfFr5ol6ihKr_QwZRnocjO6h9
"""

import json
with open("/content/book.json") as f:
 book = json.load(f)
print(book)

import firebase_admin
from firebase_admin import credentials, db
cred = credentials.Certificate("/content/firebase_key.json.json")
firebase_admin.initialize_app(cred, {
 "databaseURL": "https://dlia-lachica-grade8-library-db-default-rtdb.asia-southeast1.firebasedatabase.app/"
})
print("Firebase connected successfully!")

import json
with open("/content/book.json", "r") as file:
 data = json.load(file)
print("JSON file loaded")
ref = db.reference("books") # Changed from "students" to "books"
for book_item in data["books"]: # Changed from data["students"] to data["books"]
 ref.child(str(book_item["id"])).set(book_item) # Using book_item["id"] assuming books have an 'id'
print("Data uploaded successfully!")

books_ref = db.reference("books")
books_data = books_ref.get()
print(books_data)

for book_id, book_info in books_data.items():
 print(book_info["title"])

for book_id, book_info in books_data.items():
 print(book_info["title"], book_info["details"]["available"])

total_books = len(books_data)
print(f"Total number of books in the library: {total_books}")